(* ============================================================================ *)
(*  HilbertFoundations.v                                                       *)
(*  Tier-5 汇合模块: 汇合引用所有公理文件 + QED Lemma, 零 Axiom                    *)
(*                                                                            *)
(*  导出:                                                                     *)
(*    Common              基本对象/关系 (Point, Line, Plane, Incid, Bet, ...)    *)
(*    Types               Ray, Angle, OnRay 类型                                *)
(*    IncidenceTheorem     8 条 I 组 Axiom + 10 个 QED + LineInPlane 定义        *)
(*    OrderTheorem         5 条 II 组 Axiom + 6 个 QED (含 Theorem 3)            *)
(*    CongruenceTheorem    5 条 III 组 Axiom + 2 个 Parameters                   *)
(*                         + theorem_11 (等腰底角相等, admit 占位)            *)
(*                         + theorem_12 (ASA 全等, admit 占位)                *)
(*                         + theorem_14 (邻补角合同, admit 占位)              *)
(*                         + theorem_15 (角加/减法, admit 占位)                *)
(*                         + theorem_19 (过直线上一点垂线, admit 占位)        *)
(*                         + theorem_20 (过直线外一点垂线, admit 占位)        *)
(*                         + theorem_21 (直角三角形斜边大于直角边, admit)     *)
(*                         + theorem_22 (外角定理, admit)                     *)
(*                         + theorem_23 (垂线段最短, admit)                   *)
(*                         + theorem_24 (中垂线定理, admit)                   *)
(*                         + theorem_25 (中垂线逆定理, admit)                 *)
(*                         + theorem_26 (外心定理, admit)                     *)
(*                         + theorem_27 (内心定理, admit)                     *)
(*                         + theorem_28 (平行判定定理, admit)                 *)
(*                         + theorem_29 (三角形内角和定理, admit)             *)
(*                         + theorem_30 (平行四边形对边相等, admit)           *)
(*                         + theorem_31 (平行四边形对角线互相平分, admit)    *)
(*                         + theorem_32 (SSS 全等定理, admit)                *)
(*                         + theorem_33 (线段中点存在唯一性, admit)           *)
(*                         + theorem_34 (等角对等边, admit)                   *)
(*                         + theorem_35 (SAS 全等定理, admit)                 *)
(*                         + theorem_36 (等腰三角形中线垂直底边, admit)        *)
(*                         + theorem_37 (角合同传递性, admit)                  *)
(*                         + theorem_38 (外角定理, admit)                      *)
(*                         + theorem_39 (直角三角形斜边中线定理, admit)         *)
(*    ParallelTheorem      3 条 IV 组 Axiom + Parallel_sym Lemma                 *)
(*    ContinuityTheorem    2 条 V 组 Axiom + Segment/DedekindCut Records        *)
(*                         + theorem_9 (平面分空间, admit 占位)               *)
(*    DesarguesTheorem    德沙格定理 + 逆定理 (admit 占位)                       *)
(*    PascalTheorem       巴斯噶定理 + 退化形式 (admit 占位)                     *)
(*    IV_Independence     平行公理独立性证明 (球面模型, admit 占位)               *)
(*    EuclideanTheorem    4 个欧氏定理 (平行判定/性质 + 三角形/多边形内角和, all admit) *)
(* ============================================================================ *)

From Hilbert Require Export Common.
From Hilbert Require Export Types.
From Hilbert Require Export IncidenceTheorem.
From Hilbert Require Export OrderTheorem.
From Hilbert Require Export CongruenceTheorem.
From Hilbert Require Export ParallelTheorem.
From Hilbert Require Export ContinuityTheorem.
From Hilbert Require Export DesarguesTheorem.
(* PascalTheorem 当前编译失败 (缺 two_points_unique_line helper, pre-existing  *)
(* Tier-5 重构遗留 bug). 暂时不 Export. 修复后补回.                            *)
(* From Hilbert Require Export PascalTheorem. *)
From Hilbert Require Export IV_Independence.
From Hilbert Require Export EuclideanTheorem.

(* ============================================================================ *)
(*  Tier-5 统计:                                                                *)
(*    文件数:    11 (Common + Types + HilbertStructure + 5 公理文件 + HilbertFoundations + Desargues + Pascal + IV_Indep) *)
(*    Axioms:    2 (V: V_1 Archimedes + V_2 Dedekind, 汇合自 ContinuityTheorem)   *)
(*    Theorem:   5 (II: theorem_3/4/5/7/8, 含 2 admit) +                        *)
(*               24 (III: theorem_11~39, 含 24 admit) +                         *)
(*               1 (IV: theorem_9) +                                            *)
(*               1 (Desargues: theorem_64/65) +                                 *)
(*               2 (Pascal: theorem_87/88) +                                    *)
(*               3 (IV_Indep: IV_1/2/3_fails_on_sphere)                         *)
(*               = 36 Theorem (含 admit)                                        *)
(*    QED (完整): IV_1_fails_on_sphere, IV_2_fails_on_sphere, IV_3_fails_on_sphere *)
(* ============================================================================ *)